export const SEARCHED_DATA_LOADING = "SEARCHED_DATA_LOADING";
export const SEARCHED_DATA_SUCCESS = "SEARCHED_DATA_SUCCESS";
export const SEARCHED_DATA_FAILURE = "SEARCHED_DATA_FAILURE";

export const FOLLOWERS_DATA_LOADING = "FOLLOWERS_DATA_LOADING";
export const FOLLOWERS_DATA_SUCCESS = "FOLLOWERS_DATA_SUCCESS";
export const FOLLOWERS_DATA_FAILURE = "FOLLOWERS_DATA_FAILURE";
